/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sat Aug 03 15:19:47 2019. */

#ifndef PB_PROTO_TEST_PB_H_INCLUDED
#define PB_PROTO_TEST_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _proto_AirCondition {
    uint32_t CarId;
    uint64_t Timestamp;
    float ActualAirConditioningLoad;
    int32_t SetTemperature;
    int32_t CarOutsideTemperature;
    int32_t CarInsideTemperature;
    float DirectCurrentelEctricity;
    uint32_t AirConditionerStatusReady;
    uint32_t AirConditionerStatusBreakdown;
    uint32_t AirConditionerStatusStart;
    uint32_t LifeValue;
/* @@protoc_insertion_point(struct:proto_AirCondition) */
} proto_AirCondition;

typedef struct _proto_Bms1 {
    uint32_t CarId;
    uint64_t Timestamp;
    float TotalBatteryVoltage;
    float RechargeDischargeElectricity;
    float SOCValue;
    uint32_t PressureBig;
    uint32_t TotalOvervoltage;
    uint32_t TotalUndervoltage;
    uint32_t InsideCommunicationFail;
    uint32_t SOCLow;
    uint32_t SOCHigt;
    uint32_t MonocaseUndervoltage;
    uint32_t MonocaseOvervoltage;
    uint32_t TemperatureOverSize;
    uint32_t TemperatureRiseOversize;
    uint32_t TemperatureOverTop;
    uint32_t RechargeElectricityOverSize;
    uint32_t DischargeElectricityOverSize;
    uint32_t InsulationAlarm;
    uint32_t SmogAlarm;
    uint32_t CellTemperatureOverSize;
    uint32_t FuseStatus;
    uint32_t CurrentRechargeStatus;
    uint32_t RechargeConnectSureSignal;
    uint32_t CommunicationWithBatteryCharger;
    uint32_t HaveCapacitySmallCell;
    uint32_t HaveResistanceBigCell;
    uint32_t InsideContactorSignal;
    uint32_t RadiatSystemRunning;
/* @@protoc_insertion_point(struct:proto_Bms1) */
} proto_Bms1;

typedef struct _proto_Bms10 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t CellNum1;
    float CellVoltage1;
    uint32_t CellNum2;
    float CellVoltage2;
/* @@protoc_insertion_point(struct:proto_Bms10) */
} proto_Bms10;

typedef struct _proto_Bms11 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t ForwardSamplingSite1Number;
    int32_t ForwardSamplingSite1Temperature;
    uint32_t ForwardSamplingSite2Number;
    int32_t ForwardSamplingSite2Temperature;
    uint32_t ForwardSamplingSite3Number;
    int32_t ForwardSamplingSite3Temperature;
    uint32_t ForwardSamplingSite4Number;
    int32_t ForwardSamplingSite4Temperature;
/* @@protoc_insertion_point(struct:proto_Bms11) */
} proto_Bms11;

typedef struct _proto_Bms12 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t ForwardSamplingSite5Number;
    int32_t ForwardSamplingSite5Temperature;
    uint32_t NegativeSamplingSite1Number;
    int32_t NegativeSamplingSite1Temperature;
    uint32_t NegativeSamplingSite2Number;
    int32_t NegativeSamplingSite2Temperature;
    uint32_t NegativeSamplingSite3Number;
    int32_t NegativeSamplingSite3Temperature;
/* @@protoc_insertion_point(struct:proto_Bms12) */
} proto_Bms12;

typedef struct _proto_Bms13 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t NegativeSamplingSite4Number;
    int32_t NegativeSamplingSite4Temperature;
    uint32_t NegativeSamplingSite5Number;
    int32_t NegativeSamplingSite5Temperature;
/* @@protoc_insertion_point(struct:proto_Bms13) */
} proto_Bms13;

typedef struct _proto_Bms14 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t SamplingSite1Number;
    int32_t SamplingSite1Temperature;
    uint32_t SamplingSite2Number;
    int32_t SamplingSite2Temperature;
    uint32_t SamplingSite3Number;
    int32_t SamplingSite3Temperature;
    uint32_t SamplingSite4Number;
    int32_t SamplingSite4Temperature;
/* @@protoc_insertion_point(struct:proto_Bms14) */
} proto_Bms14;

typedef struct _proto_Bms15 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t CellPermissibleDisconnectionIdentification;
    uint32_t MainContactorRequestStatus;
    uint32_t ElectricDefrostingContactorRequestStatus;
    uint32_t ElectricHeatingContactorRequestStatus;
    uint32_t ACContactorRequestStatus;
/* @@protoc_insertion_point(struct:proto_Bms15) */
} proto_Bms15;

typedef struct _proto_Bms2 {
    uint32_t CarId;
    uint64_t Timestamp;
    float CurrentMaxAllowRechargeElectricity;
    float CurrentMaxAllowDischargeElectricity;
    uint32_t LiPoSystemBreakdownClass;
    float MonomerMeanVoltage;
    int32_t MonomerMaxTemperature;
/* @@protoc_insertion_point(struct:proto_Bms2) */
} proto_Bms2;

typedef struct _proto_Bms3 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t PositiveInsulatingResistance;
    uint32_t NegativeInsulatingResistance;
    float CellVoltageMaxValue;
    float CellVoltageMinValue;
/* @@protoc_insertion_point(struct:proto_Bms3) */
} proto_Bms3;

typedef struct _proto_Bms4 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t VINAcceptStatus;
    uint32_t AssistContactorGlue;
    uint32_t ChargingContactorStatus;
    uint32_t CellCathodeContactorGlue;
    uint32_t CellAnodeContactorGlue;
    uint32_t MSDStatus;
    uint32_t WirelessRechargeConnectSignal;
    uint32_t ChargingStationOverTemperatureTemperature;
    uint32_t FireExtinguisherAlarm;
    int32_t ChargingStationTemperature1;
    int32_t ChargingStationTemperature2;
    int32_t ChargingStationTemperature3;
    int32_t ChargingStationTemperature4;
    uint32_t ActiveBreakdownCount;
    uint32_t ChargeComplete;
    uint32_t WarmModuleTurnoff;
    uint32_t HighPressureTurnoff;
    uint32_t CellSystemPilesUnmatched;
    uint32_t CellOverRecharge;
    uint32_t SOCSaltusStep;
/* @@protoc_insertion_point(struct:proto_Bms4) */
} proto_Bms4;

typedef struct _proto_Bms5 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t CellSystemRatedCapacity;
    float CellSystemRatedVoltage;
    uint32_t CellMonomerCascadeNumber;
    uint32_t CellMonomerMultipleNumber;
    uint32_t CellSystemTemperatureProbeNumber;
/* @@protoc_insertion_point(struct:proto_Bms5) */
} proto_Bms5;

typedef struct _proto_Bms6 {
    uint32_t CarId;
    uint64_t Timestamp;
    int32_t CellTemperatureMaxValue;
    uint32_t CellMaxTemperatureCode;
    uint32_t CellMaxTemperatureNum;
    int32_t CellTemperatureMinValue;
    uint32_t CellMinTemperatureCode;
    uint32_t CellMinTemperatureNum;
    uint32_t CellTypeInfo;
    uint32_t CellCollMode;
/* @@protoc_insertion_point(struct:proto_Bms6) */
} proto_Bms6;

typedef struct _proto_Bms7 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t CellMaxVoltageCode;
    uint32_t CellMaxVoltageNum;
    uint32_t CellMinVoltageCode;
    uint32_t CellMinVoltageNum;
/* @@protoc_insertion_point(struct:proto_Bms7) */
} proto_Bms7;

typedef struct _proto_Bms8 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t ForwardCellNum1;
    float ForwardCellVoltage1;
    uint32_t ForwardCellNum2;
    float ForwardCellVoltage2;
/* @@protoc_insertion_point(struct:proto_Bms8) */
} proto_Bms8;

typedef struct _proto_Bms9 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t ForwardCellNum5;
    float ForwardCellVoltage5;
    uint32_t NegativeCellNum1;
    float NegativeCellVoltage1;
/* @@protoc_insertion_point(struct:proto_Bms9) */
} proto_Bms9;

typedef struct _proto_Meter1 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t KeyFirstGearSignal;
    uint32_t KeyTwoGearSignal;
    uint32_t BackDoorOpenSignal;
    uint32_t FrontDoorOpenSignal;
    uint32_t RearCompartmentDoorOpenSignal;
    uint32_t ParkingSignal;
    uint32_t VehicleLowPressureAlarm;
    uint32_t TurnLeftInstruction;
    uint32_t FarLightInstruction;
    uint32_t FrontMistInstruction;
    uint32_t TurnRightInstruction;
    uint32_t OilMassAlarm;
    uint32_t EnginePreheat;
    uint32_t NearLightInstruction;
    uint32_t BackMistInstruction;
    float VehicleSpeed;
    float AirPressureOne;
    float AirPressureTwo;
/* @@protoc_insertion_point(struct:proto_Meter1) */
} proto_Meter1;

typedef struct _proto_Meter2 {
    uint32_t CarId;
    uint64_t Timestamp;
    float MeterTotalMileage;
    float MeterPartMileage;
/* @@protoc_insertion_point(struct:proto_Meter2) */
} proto_Meter2;

typedef struct _proto_ObuTrafficLightsRequest {
    uint32_t VechicleId;
    uint64_t Timestamp;
    double VechicleLongitude;
    double VechicleLatitude;
    double VechicleHeading;
    double VechicleSpeed;
    uint32_t VechicleForwardTurning;
    uint32_t VechicleLaneChangingIntention;
    uint32_t VechicleSpeedChangeIntention;
    uint32_t TrafficId;
    uint32_t TrafficDirection;
    uint32_t TrafficTrace;
    uint32_t TrafficSignal;
    uint32_t TrafficDelay;
/* @@protoc_insertion_point(struct:proto_ObuTrafficLightsRequest) */
} proto_ObuTrafficLightsRequest;

typedef struct _proto_ObuTrafficLightsResponse {
    uint32_t VechicleId;
    uint64_t Timestamp;
    pb_callback_t Code;
/* @@protoc_insertion_point(struct:proto_ObuTrafficLightsResponse) */
} proto_ObuTrafficLightsResponse;

typedef struct _proto_OilPump1 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t MotorSpeed;
    uint32_t HeartbeatSignal;
    uint32_t HighVoltageFaultMarkerBit;
    uint32_t HighVoltageFaultRating;
/* @@protoc_insertion_point(struct:proto_OilPump1) */
} proto_OilPump1;

typedef struct _proto_OilPump2 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t OilPumpEnabled;
    uint32_t VehicleSpeed;
/* @@protoc_insertion_point(struct:proto_OilPump2) */
} proto_OilPump2;

typedef struct _proto_RoadBlockRequest {
    uint32_t RsuId;
    uint64_t Timestamp;
    float SpeedLimit;
    float latitude;
    float longitude;
/* @@protoc_insertion_point(struct:proto_RoadBlockRequest) */
} proto_RoadBlockRequest;

typedef struct _proto_RoadBlockResponse {
    uint32_t RsuId;
    uint64_t Time;
    uint32_t Color;
    float SpeedLimit;
/* @@protoc_insertion_point(struct:proto_RoadBlockResponse) */
} proto_RoadBlockResponse;

typedef struct _proto_RsuInfoRequest {
    uint32_t RsuId;
    uint64_t Timestamp;
    uint32_t NorthSignalL;
    uint32_t NorthDelayL;
    uint32_t NorthSignalD;
    uint32_t NorthDelayD;
    uint32_t NorthSignalR;
    uint32_t NorthDelayR;
    uint32_t SouthSignalL;
    uint32_t SouthDelayL;
    uint32_t SouthSignalD;
    uint32_t SouthDelayD;
    uint32_t SouthSignalR;
    uint32_t SouthDelayR;
    uint32_t WestSignalL;
    uint32_t WestDelayL;
    uint32_t WestSignalD;
    uint32_t WestDelayD;
    uint32_t WestSignalR;
    uint32_t WestDelayR;
    uint32_t EastSignalL;
    uint32_t EastDelayL;
    uint32_t EastSignalD;
    uint32_t EastDelayD;
    uint32_t EastSignalR;
    uint32_t EastDelayR;
    uint32_t SensorRain;
    uint32_t SensorWaterLogged;
    uint32_t SensorVisibility;
/* @@protoc_insertion_point(struct:proto_RsuInfoRequest) */
} proto_RsuInfoRequest;

typedef struct _proto_RsuInfoResponse {
    uint32_t RsuId;
    uint64_t Timestamp;
    pb_callback_t Code;
/* @@protoc_insertion_point(struct:proto_RsuInfoResponse) */
} proto_RsuInfoResponse;

typedef struct _proto_Vcu1 {
    uint32_t CarId;
    uint64_t Timestamp;
    float MotorControlInputVoltage;
    float MotorControlInputCurrent;
    int32_t MotorTorque;
    int32_t MotorSpeed;
/* @@protoc_insertion_point(struct:proto_Vcu1) */
} proto_Vcu1;

typedef struct _proto_Vcu2 {
    uint32_t CarId;
    uint64_t Timestamp;
    int32_t MotorTemperatur;
    int32_t MotorControlTemperature;
    uint32_t HighVoltageSwitch;
    uint32_t PowerMode;
    uint32_t ClimbMode;
    uint32_t Gear;
    uint32_t EffectiveElectricBrak;
    uint32_t ChargDetectionSignal;
    uint32_t AirConditionerSignal;
    uint32_t PrechargeContactor;
    uint32_t MasterContactor;
    uint32_t SystemDemo;
/* @@protoc_insertion_point(struct:proto_Vcu2) */
} proto_Vcu2;

typedef struct _proto_Vcu3 {
    uint32_t CarId;
    uint64_t Timestamp;
    float TractionPedalPercent;
    float BrakePedalPercent;
/* @@protoc_insertion_point(struct:proto_Vcu3) */
} proto_Vcu3;

typedef struct _proto_Vcu4 {
    uint32_t CarId;
    uint64_t Timestamp;
    uint32_t VehicleModel;
    uint32_t VehicleSystem;
    uint32_t ElectricalMachinery;
/* @@protoc_insertion_point(struct:proto_Vcu4) */
} proto_Vcu4;

typedef struct _proto_position_data_t {
    uint32_t CarId;
    double latitude;
    double longitude;
    double heading;
    double velocity;
    double speed;
    double trace;
/* @@protoc_insertion_point(struct:proto_position_data_t) */
} proto_position_data_t;

typedef struct _proto_uwb {
    uint32_t CarId;
    uint64_t Timestamp;
    bool NorthHemisphere;
    bool EastHemisphere;
    float Latitude;
    float Longitude;
/* @@protoc_insertion_point(struct:proto_uwb) */
} proto_uwb;

typedef struct _proto_CANMessage {
    proto_Vcu1 Vcu1Msg;
    proto_Vcu2 Vcu2Msg;
    proto_Vcu3 Vcu3Msg;
    proto_Vcu4 Vcu4Msg;
    proto_Meter1 Meter1Msg;
    proto_Meter2 Meter2Msg;
    proto_AirCondition AirConditionMsg;
    proto_Bms1 Bms1Msg;
    proto_Bms2 Bms2Msg;
    proto_Bms3 Bms3Msg;
    proto_Bms4 Bms4Msg;
    proto_Bms5 Bms5Msg;
    proto_Bms6 Bms6Msg;
    proto_Bms7 Bms7Msg;
    proto_Bms8 Bms8Msg;
    proto_Bms9 Bms9Msg;
    proto_Bms10 Bms10Msg;
    proto_Bms11 Bms11Msg;
    proto_Bms12 Bms12Msg;
    proto_Bms13 Bms13Msg;
    proto_Bms14 Bms14Msg;
    proto_Bms15 Bms15Msg;
    proto_OilPump1 OilPump1Msg;
    proto_OilPump2 OilPump2Msg;
/* @@protoc_insertion_point(struct:proto_CANMessage) */
} proto_CANMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define proto_RsuInfoRequest_init_default        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_RsuInfoResponse_init_default       {0, 0, {{NULL}, NULL}}
#define proto_ObuTrafficLightsRequest_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_ObuTrafficLightsResponse_init_default {0, 0, {{NULL}, NULL}}
#define proto_RoadBlockRequest_init_default      {0, 0, 0, 0, 0}
#define proto_RoadBlockResponse_init_default     {0, 0, 0, 0}
#define proto_uwb_init_default                   {0, 0, 0, 0, 0, 0}
#define proto_Vcu1_init_default                  {0, 0, 0, 0, 0, 0}
#define proto_Vcu2_init_default                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Vcu3_init_default                  {0, 0, 0, 0}
#define proto_Vcu4_init_default                  {0, 0, 0, 0, 0}
#define proto_Meter1_init_default                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Meter2_init_default                {0, 0, 0, 0}
#define proto_AirCondition_init_default          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms1_init_default                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms2_init_default                  {0, 0, 0, 0, 0, 0, 0}
#define proto_Bms3_init_default                  {0, 0, 0, 0, 0, 0}
#define proto_Bms4_init_default                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms5_init_default                  {0, 0, 0, 0, 0, 0, 0}
#define proto_Bms6_init_default                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms7_init_default                  {0, 0, 0, 0, 0, 0}
#define proto_Bms8_init_default                  {0, 0, 0, 0, 0, 0}
#define proto_Bms9_init_default                  {0, 0, 0, 0, 0, 0}
#define proto_Bms10_init_default                 {0, 0, 0, 0, 0, 0}
#define proto_Bms11_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms12_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms13_init_default                 {0, 0, 0, 0, 0, 0}
#define proto_Bms14_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms15_init_default                 {0, 0, 0, 0, 0, 0, 0}
#define proto_OilPump1_init_default              {0, 0, 0, 0, 0, 0}
#define proto_OilPump2_init_default              {0, 0, 0, 0}
#define proto_CANMessage_init_default            {proto_Vcu1_init_default, proto_Vcu2_init_default, proto_Vcu3_init_default, proto_Vcu4_init_default, proto_Meter1_init_default, proto_Meter2_init_default, proto_AirCondition_init_default, proto_Bms1_init_default, proto_Bms2_init_default, proto_Bms3_init_default, proto_Bms4_init_default, proto_Bms5_init_default, proto_Bms6_init_default, proto_Bms7_init_default, proto_Bms8_init_default, proto_Bms9_init_default, proto_Bms10_init_default, proto_Bms11_init_default, proto_Bms12_init_default, proto_Bms13_init_default, proto_Bms14_init_default, proto_Bms15_init_default, proto_OilPump1_init_default, proto_OilPump2_init_default}
#define proto_position_data_t_init_default       {0, 0, 0, 0, 0, 0, 0}
#define proto_RsuInfoRequest_init_zero           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_RsuInfoResponse_init_zero          {0, 0, {{NULL}, NULL}}
#define proto_ObuTrafficLightsRequest_init_zero  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_ObuTrafficLightsResponse_init_zero {0, 0, {{NULL}, NULL}}
#define proto_RoadBlockRequest_init_zero         {0, 0, 0, 0, 0}
#define proto_RoadBlockResponse_init_zero        {0, 0, 0, 0}
#define proto_uwb_init_zero                      {0, 0, 0, 0, 0, 0}
#define proto_Vcu1_init_zero                     {0, 0, 0, 0, 0, 0}
#define proto_Vcu2_init_zero                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Vcu3_init_zero                     {0, 0, 0, 0}
#define proto_Vcu4_init_zero                     {0, 0, 0, 0, 0}
#define proto_Meter1_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Meter2_init_zero                   {0, 0, 0, 0}
#define proto_AirCondition_init_zero             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms1_init_zero                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms2_init_zero                     {0, 0, 0, 0, 0, 0, 0}
#define proto_Bms3_init_zero                     {0, 0, 0, 0, 0, 0}
#define proto_Bms4_init_zero                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms5_init_zero                     {0, 0, 0, 0, 0, 0, 0}
#define proto_Bms6_init_zero                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms7_init_zero                     {0, 0, 0, 0, 0, 0}
#define proto_Bms8_init_zero                     {0, 0, 0, 0, 0, 0}
#define proto_Bms9_init_zero                     {0, 0, 0, 0, 0, 0}
#define proto_Bms10_init_zero                    {0, 0, 0, 0, 0, 0}
#define proto_Bms11_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms12_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms13_init_zero                    {0, 0, 0, 0, 0, 0}
#define proto_Bms14_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define proto_Bms15_init_zero                    {0, 0, 0, 0, 0, 0, 0}
#define proto_OilPump1_init_zero                 {0, 0, 0, 0, 0, 0}
#define proto_OilPump2_init_zero                 {0, 0, 0, 0}
#define proto_CANMessage_init_zero               {proto_Vcu1_init_zero, proto_Vcu2_init_zero, proto_Vcu3_init_zero, proto_Vcu4_init_zero, proto_Meter1_init_zero, proto_Meter2_init_zero, proto_AirCondition_init_zero, proto_Bms1_init_zero, proto_Bms2_init_zero, proto_Bms3_init_zero, proto_Bms4_init_zero, proto_Bms5_init_zero, proto_Bms6_init_zero, proto_Bms7_init_zero, proto_Bms8_init_zero, proto_Bms9_init_zero, proto_Bms10_init_zero, proto_Bms11_init_zero, proto_Bms12_init_zero, proto_Bms13_init_zero, proto_Bms14_init_zero, proto_Bms15_init_zero, proto_OilPump1_init_zero, proto_OilPump2_init_zero}
#define proto_position_data_t_init_zero          {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define proto_AirCondition_CarId_tag             1
#define proto_AirCondition_Timestamp_tag         2
#define proto_AirCondition_ActualAirConditioningLoad_tag 3
#define proto_AirCondition_SetTemperature_tag    4
#define proto_AirCondition_CarOutsideTemperature_tag 5
#define proto_AirCondition_CarInsideTemperature_tag 6
#define proto_AirCondition_DirectCurrentelEctricity_tag 7
#define proto_AirCondition_AirConditionerStatusReady_tag 8
#define proto_AirCondition_AirConditionerStatusBreakdown_tag 9
#define proto_AirCondition_AirConditionerStatusStart_tag 10
#define proto_AirCondition_LifeValue_tag         11
#define proto_Bms1_CarId_tag                     1
#define proto_Bms1_Timestamp_tag                 2
#define proto_Bms1_TotalBatteryVoltage_tag       3
#define proto_Bms1_RechargeDischargeElectricity_tag 4
#define proto_Bms1_SOCValue_tag                  5
#define proto_Bms1_PressureBig_tag               6
#define proto_Bms1_TotalOvervoltage_tag          7
#define proto_Bms1_TotalUndervoltage_tag         8
#define proto_Bms1_InsideCommunicationFail_tag   9
#define proto_Bms1_SOCLow_tag                    10
#define proto_Bms1_SOCHigt_tag                   11
#define proto_Bms1_MonocaseUndervoltage_tag      12
#define proto_Bms1_MonocaseOvervoltage_tag       13
#define proto_Bms1_TemperatureOverSize_tag       14
#define proto_Bms1_TemperatureRiseOversize_tag   15
#define proto_Bms1_TemperatureOverTop_tag        16
#define proto_Bms1_RechargeElectricityOverSize_tag 17
#define proto_Bms1_DischargeElectricityOverSize_tag 18
#define proto_Bms1_InsulationAlarm_tag           19
#define proto_Bms1_SmogAlarm_tag                 20
#define proto_Bms1_CellTemperatureOverSize_tag   21
#define proto_Bms1_FuseStatus_tag                22
#define proto_Bms1_CurrentRechargeStatus_tag     23
#define proto_Bms1_RechargeConnectSureSignal_tag 24
#define proto_Bms1_CommunicationWithBatteryCharger_tag 25
#define proto_Bms1_HaveCapacitySmallCell_tag     26
#define proto_Bms1_HaveResistanceBigCell_tag     27
#define proto_Bms1_InsideContactorSignal_tag     28
#define proto_Bms1_RadiatSystemRunning_tag       29
#define proto_Bms10_CarId_tag                    1
#define proto_Bms10_Timestamp_tag                2
#define proto_Bms10_CellNum1_tag                 3
#define proto_Bms10_CellVoltage1_tag             4
#define proto_Bms10_CellNum2_tag                 5
#define proto_Bms10_CellVoltage2_tag             6
#define proto_Bms11_CarId_tag                    1
#define proto_Bms11_Timestamp_tag                2
#define proto_Bms11_ForwardSamplingSite1Number_tag 3
#define proto_Bms11_ForwardSamplingSite1Temperature_tag 4
#define proto_Bms11_ForwardSamplingSite2Number_tag 5
#define proto_Bms11_ForwardSamplingSite2Temperature_tag 6
#define proto_Bms11_ForwardSamplingSite3Number_tag 7
#define proto_Bms11_ForwardSamplingSite3Temperature_tag 8
#define proto_Bms11_ForwardSamplingSite4Number_tag 9
#define proto_Bms11_ForwardSamplingSite4Temperature_tag 10
#define proto_Bms12_CarId_tag                    1
#define proto_Bms12_Timestamp_tag                2
#define proto_Bms12_ForwardSamplingSite5Number_tag 3
#define proto_Bms12_ForwardSamplingSite5Temperature_tag 4
#define proto_Bms12_NegativeSamplingSite1Number_tag 5
#define proto_Bms12_NegativeSamplingSite1Temperature_tag 6
#define proto_Bms12_NegativeSamplingSite2Number_tag 7
#define proto_Bms12_NegativeSamplingSite2Temperature_tag 8
#define proto_Bms12_NegativeSamplingSite3Number_tag 9
#define proto_Bms12_NegativeSamplingSite3Temperature_tag 10
#define proto_Bms13_CarId_tag                    1
#define proto_Bms13_Timestamp_tag                2
#define proto_Bms13_NegativeSamplingSite4Number_tag 3
#define proto_Bms13_NegativeSamplingSite4Temperature_tag 4
#define proto_Bms13_NegativeSamplingSite5Number_tag 5
#define proto_Bms13_NegativeSamplingSite5Temperature_tag 6
#define proto_Bms14_CarId_tag                    1
#define proto_Bms14_Timestamp_tag                2
#define proto_Bms14_SamplingSite1Number_tag      3
#define proto_Bms14_SamplingSite1Temperature_tag 4
#define proto_Bms14_SamplingSite2Number_tag      5
#define proto_Bms14_SamplingSite2Temperature_tag 6
#define proto_Bms14_SamplingSite3Number_tag      7
#define proto_Bms14_SamplingSite3Temperature_tag 8
#define proto_Bms14_SamplingSite4Number_tag      9
#define proto_Bms14_SamplingSite4Temperature_tag 10
#define proto_Bms15_CarId_tag                    1
#define proto_Bms15_Timestamp_tag                2
#define proto_Bms15_CellPermissibleDisconnectionIdentification_tag 3
#define proto_Bms15_MainContactorRequestStatus_tag 4
#define proto_Bms15_ElectricDefrostingContactorRequestStatus_tag 5
#define proto_Bms15_ElectricHeatingContactorRequestStatus_tag 6
#define proto_Bms15_ACContactorRequestStatus_tag 7
#define proto_Bms2_CarId_tag                     1
#define proto_Bms2_Timestamp_tag                 2
#define proto_Bms2_CurrentMaxAllowRechargeElectricity_tag 3
#define proto_Bms2_CurrentMaxAllowDischargeElectricity_tag 4
#define proto_Bms2_LiPoSystemBreakdownClass_tag  5
#define proto_Bms2_MonomerMeanVoltage_tag        6
#define proto_Bms2_MonomerMaxTemperature_tag     7
#define proto_Bms3_CarId_tag                     1
#define proto_Bms3_Timestamp_tag                 2
#define proto_Bms3_PositiveInsulatingResistance_tag 3
#define proto_Bms3_NegativeInsulatingResistance_tag 4
#define proto_Bms3_CellVoltageMaxValue_tag       5
#define proto_Bms3_CellVoltageMinValue_tag       6
#define proto_Bms4_CarId_tag                     1
#define proto_Bms4_Timestamp_tag                 2
#define proto_Bms4_VINAcceptStatus_tag           3
#define proto_Bms4_AssistContactorGlue_tag       4
#define proto_Bms4_ChargingContactorStatus_tag   5
#define proto_Bms4_CellCathodeContactorGlue_tag  6
#define proto_Bms4_CellAnodeContactorGlue_tag    7
#define proto_Bms4_MSDStatus_tag                 8
#define proto_Bms4_WirelessRechargeConnectSignal_tag 9
#define proto_Bms4_ChargingStationOverTemperatureTemperature_tag 10
#define proto_Bms4_FireExtinguisherAlarm_tag     11
#define proto_Bms4_ChargingStationTemperature1_tag 12
#define proto_Bms4_ChargingStationTemperature2_tag 13
#define proto_Bms4_ChargingStationTemperature3_tag 14
#define proto_Bms4_ChargingStationTemperature4_tag 15
#define proto_Bms4_ActiveBreakdownCount_tag      16
#define proto_Bms4_ChargeComplete_tag            17
#define proto_Bms4_WarmModuleTurnoff_tag         18
#define proto_Bms4_HighPressureTurnoff_tag       19
#define proto_Bms4_CellSystemPilesUnmatched_tag  20
#define proto_Bms4_CellOverRecharge_tag          21
#define proto_Bms4_SOCSaltusStep_tag             22
#define proto_Bms5_CarId_tag                     1
#define proto_Bms5_Timestamp_tag                 2
#define proto_Bms5_CellSystemRatedCapacity_tag   3
#define proto_Bms5_CellSystemRatedVoltage_tag    4
#define proto_Bms5_CellMonomerCascadeNumber_tag  5
#define proto_Bms5_CellMonomerMultipleNumber_tag 6
#define proto_Bms5_CellSystemTemperatureProbeNumber_tag 7
#define proto_Bms6_CarId_tag                     1
#define proto_Bms6_Timestamp_tag                 2
#define proto_Bms6_CellTemperatureMaxValue_tag   3
#define proto_Bms6_CellMaxTemperatureCode_tag    4
#define proto_Bms6_CellMaxTemperatureNum_tag     5
#define proto_Bms6_CellTemperatureMinValue_tag   6
#define proto_Bms6_CellMinTemperatureCode_tag    7
#define proto_Bms6_CellMinTemperatureNum_tag     8
#define proto_Bms6_CellTypeInfo_tag              9
#define proto_Bms6_CellCollMode_tag              10
#define proto_Bms7_CarId_tag                     1
#define proto_Bms7_Timestamp_tag                 2
#define proto_Bms7_CellMaxVoltageCode_tag        3
#define proto_Bms7_CellMaxVoltageNum_tag         4
#define proto_Bms7_CellMinVoltageCode_tag        5
#define proto_Bms7_CellMinVoltageNum_tag         6
#define proto_Bms8_CarId_tag                     1
#define proto_Bms8_Timestamp_tag                 2
#define proto_Bms8_ForwardCellNum1_tag           3
#define proto_Bms8_ForwardCellVoltage1_tag       4
#define proto_Bms8_ForwardCellNum2_tag           5
#define proto_Bms8_ForwardCellVoltage2_tag       6
#define proto_Bms9_CarId_tag                     1
#define proto_Bms9_Timestamp_tag                 2
#define proto_Bms9_ForwardCellNum5_tag           3
#define proto_Bms9_ForwardCellVoltage5_tag       4
#define proto_Bms9_NegativeCellNum1_tag          5
#define proto_Bms9_NegativeCellVoltage1_tag      6
#define proto_Meter1_CarId_tag                   1
#define proto_Meter1_Timestamp_tag               2
#define proto_Meter1_KeyFirstGearSignal_tag      3
#define proto_Meter1_KeyTwoGearSignal_tag        4
#define proto_Meter1_BackDoorOpenSignal_tag      5
#define proto_Meter1_FrontDoorOpenSignal_tag     6
#define proto_Meter1_RearCompartmentDoorOpenSignal_tag 7
#define proto_Meter1_ParkingSignal_tag           8
#define proto_Meter1_VehicleLowPressureAlarm_tag 9
#define proto_Meter1_TurnLeftInstruction_tag     10
#define proto_Meter1_FarLightInstruction_tag     11
#define proto_Meter1_FrontMistInstruction_tag    12
#define proto_Meter1_TurnRightInstruction_tag    13
#define proto_Meter1_OilMassAlarm_tag            14
#define proto_Meter1_EnginePreheat_tag           15
#define proto_Meter1_NearLightInstruction_tag    16
#define proto_Meter1_BackMistInstruction_tag     17
#define proto_Meter1_VehicleSpeed_tag            18
#define proto_Meter1_AirPressureOne_tag          19
#define proto_Meter1_AirPressureTwo_tag          20
#define proto_Meter2_CarId_tag                   1
#define proto_Meter2_Timestamp_tag               2
#define proto_Meter2_MeterTotalMileage_tag       3
#define proto_Meter2_MeterPartMileage_tag        4
#define proto_ObuTrafficLightsRequest_VechicleId_tag 1
#define proto_ObuTrafficLightsRequest_Timestamp_tag 2
#define proto_ObuTrafficLightsRequest_VechicleLongitude_tag 3
#define proto_ObuTrafficLightsRequest_VechicleLatitude_tag 4
#define proto_ObuTrafficLightsRequest_VechicleHeading_tag 5
#define proto_ObuTrafficLightsRequest_VechicleSpeed_tag 6
#define proto_ObuTrafficLightsRequest_VechicleForwardTurning_tag 7
#define proto_ObuTrafficLightsRequest_VechicleLaneChangingIntention_tag 8
#define proto_ObuTrafficLightsRequest_VechicleSpeedChangeIntention_tag 9
#define proto_ObuTrafficLightsRequest_TrafficId_tag 10
#define proto_ObuTrafficLightsRequest_TrafficDirection_tag 11
#define proto_ObuTrafficLightsRequest_TrafficTrace_tag 12
#define proto_ObuTrafficLightsRequest_TrafficSignal_tag 13
#define proto_ObuTrafficLightsRequest_TrafficDelay_tag 14
#define proto_ObuTrafficLightsResponse_VechicleId_tag 1
#define proto_ObuTrafficLightsResponse_Timestamp_tag 2
#define proto_ObuTrafficLightsResponse_Code_tag  3
#define proto_OilPump1_CarId_tag                 1
#define proto_OilPump1_Timestamp_tag             2
#define proto_OilPump1_MotorSpeed_tag            3
#define proto_OilPump1_HeartbeatSignal_tag       4
#define proto_OilPump1_HighVoltageFaultMarkerBit_tag 5
#define proto_OilPump1_HighVoltageFaultRating_tag 6
#define proto_OilPump2_CarId_tag                 1
#define proto_OilPump2_Timestamp_tag             2
#define proto_OilPump2_OilPumpEnabled_tag        3
#define proto_OilPump2_VehicleSpeed_tag          4
#define proto_RoadBlockRequest_RsuId_tag         1
#define proto_RoadBlockRequest_Timestamp_tag     2
#define proto_RoadBlockRequest_SpeedLimit_tag    3
#define proto_RoadBlockRequest_latitude_tag      4
#define proto_RoadBlockRequest_longitude_tag     5
#define proto_RoadBlockResponse_RsuId_tag        1
#define proto_RoadBlockResponse_Time_tag         2
#define proto_RoadBlockResponse_Color_tag        3
#define proto_RoadBlockResponse_SpeedLimit_tag   4
#define proto_RsuInfoRequest_RsuId_tag           1
#define proto_RsuInfoRequest_Timestamp_tag       2
#define proto_RsuInfoRequest_NorthSignalL_tag    3
#define proto_RsuInfoRequest_NorthDelayL_tag     4
#define proto_RsuInfoRequest_NorthSignalD_tag    5
#define proto_RsuInfoRequest_NorthDelayD_tag     6
#define proto_RsuInfoRequest_NorthSignalR_tag    7
#define proto_RsuInfoRequest_NorthDelayR_tag     8
#define proto_RsuInfoRequest_SouthSignalL_tag    9
#define proto_RsuInfoRequest_SouthDelayL_tag     10
#define proto_RsuInfoRequest_SouthSignalD_tag    11
#define proto_RsuInfoRequest_SouthDelayD_tag     12
#define proto_RsuInfoRequest_SouthSignalR_tag    13
#define proto_RsuInfoRequest_SouthDelayR_tag     14
#define proto_RsuInfoRequest_WestSignalL_tag     15
#define proto_RsuInfoRequest_WestDelayL_tag      16
#define proto_RsuInfoRequest_WestSignalD_tag     17
#define proto_RsuInfoRequest_WestDelayD_tag      18
#define proto_RsuInfoRequest_WestSignalR_tag     19
#define proto_RsuInfoRequest_WestDelayR_tag      20
#define proto_RsuInfoRequest_EastSignalL_tag     21
#define proto_RsuInfoRequest_EastDelayL_tag      22
#define proto_RsuInfoRequest_EastSignalD_tag     23
#define proto_RsuInfoRequest_EastDelayD_tag      24
#define proto_RsuInfoRequest_EastSignalR_tag     25
#define proto_RsuInfoRequest_EastDelayR_tag      26
#define proto_RsuInfoRequest_SensorRain_tag      27
#define proto_RsuInfoRequest_SensorWaterLogged_tag 28
#define proto_RsuInfoRequest_SensorVisibility_tag 29
#define proto_RsuInfoResponse_RsuId_tag          1
#define proto_RsuInfoResponse_Timestamp_tag      2
#define proto_RsuInfoResponse_Code_tag           3
#define proto_Vcu1_CarId_tag                     1
#define proto_Vcu1_Timestamp_tag                 2
#define proto_Vcu1_MotorControlInputVoltage_tag  3
#define proto_Vcu1_MotorControlInputCurrent_tag  4
#define proto_Vcu1_MotorTorque_tag               5
#define proto_Vcu1_MotorSpeed_tag                6
#define proto_Vcu2_CarId_tag                     1
#define proto_Vcu2_Timestamp_tag                 2
#define proto_Vcu2_MotorTemperatur_tag           3
#define proto_Vcu2_MotorControlTemperature_tag   4
#define proto_Vcu2_HighVoltageSwitch_tag         5
#define proto_Vcu2_PowerMode_tag                 6
#define proto_Vcu2_ClimbMode_tag                 7
#define proto_Vcu2_Gear_tag                      8
#define proto_Vcu2_EffectiveElectricBrak_tag     9
#define proto_Vcu2_ChargDetectionSignal_tag      10
#define proto_Vcu2_AirConditionerSignal_tag      11
#define proto_Vcu2_PrechargeContactor_tag        12
#define proto_Vcu2_MasterContactor_tag           13
#define proto_Vcu2_SystemDemo_tag                14
#define proto_Vcu3_CarId_tag                     1
#define proto_Vcu3_Timestamp_tag                 2
#define proto_Vcu3_TractionPedalPercent_tag      3
#define proto_Vcu3_BrakePedalPercent_tag         4
#define proto_Vcu4_CarId_tag                     1
#define proto_Vcu4_Timestamp_tag                 2
#define proto_Vcu4_VehicleModel_tag              3
#define proto_Vcu4_VehicleSystem_tag             4
#define proto_Vcu4_ElectricalMachinery_tag       5
#define proto_position_data_t_CarId_tag          1
#define proto_position_data_t_latitude_tag       2
#define proto_position_data_t_longitude_tag      3
#define proto_position_data_t_heading_tag        4
#define proto_position_data_t_velocity_tag       5
#define proto_position_data_t_speed_tag          6
#define proto_position_data_t_trace_tag          7
#define proto_uwb_CarId_tag                      1
#define proto_uwb_Timestamp_tag                  2
#define proto_uwb_NorthHemisphere_tag            3
#define proto_uwb_EastHemisphere_tag             4
#define proto_uwb_Latitude_tag                   5
#define proto_uwb_Longitude_tag                  6
#define proto_CANMessage_Vcu1Msg_tag             1
#define proto_CANMessage_Vcu2Msg_tag             2
#define proto_CANMessage_Vcu3Msg_tag             3
#define proto_CANMessage_Vcu4Msg_tag             4
#define proto_CANMessage_Meter1Msg_tag           5
#define proto_CANMessage_Meter2Msg_tag           6
#define proto_CANMessage_AirConditionMsg_tag     7
#define proto_CANMessage_Bms1Msg_tag             8
#define proto_CANMessage_Bms2Msg_tag             9
#define proto_CANMessage_Bms3Msg_tag             10
#define proto_CANMessage_Bms4Msg_tag             11
#define proto_CANMessage_Bms5Msg_tag             12
#define proto_CANMessage_Bms6Msg_tag             13
#define proto_CANMessage_Bms7Msg_tag             14
#define proto_CANMessage_Bms8Msg_tag             15
#define proto_CANMessage_Bms9Msg_tag             16
#define proto_CANMessage_Bms10Msg_tag            17
#define proto_CANMessage_Bms11Msg_tag            18
#define proto_CANMessage_Bms12Msg_tag            19
#define proto_CANMessage_Bms13Msg_tag            20
#define proto_CANMessage_Bms14Msg_tag            21
#define proto_CANMessage_Bms15Msg_tag            22
#define proto_CANMessage_OilPump1Msg_tag         23
#define proto_CANMessage_OilPump2Msg_tag         24

/* Struct field encoding specification for nanopb */
extern const pb_field_t proto_RsuInfoRequest_fields[30];
extern const pb_field_t proto_RsuInfoResponse_fields[4];
extern const pb_field_t proto_ObuTrafficLightsRequest_fields[15];
extern const pb_field_t proto_ObuTrafficLightsResponse_fields[4];
extern const pb_field_t proto_RoadBlockRequest_fields[6];
extern const pb_field_t proto_RoadBlockResponse_fields[5];
extern const pb_field_t proto_uwb_fields[7];
extern const pb_field_t proto_Vcu1_fields[7];
extern const pb_field_t proto_Vcu2_fields[15];
extern const pb_field_t proto_Vcu3_fields[5];
extern const pb_field_t proto_Vcu4_fields[6];
extern const pb_field_t proto_Meter1_fields[21];
extern const pb_field_t proto_Meter2_fields[5];
extern const pb_field_t proto_AirCondition_fields[12];
extern const pb_field_t proto_Bms1_fields[30];
extern const pb_field_t proto_Bms2_fields[8];
extern const pb_field_t proto_Bms3_fields[7];
extern const pb_field_t proto_Bms4_fields[23];
extern const pb_field_t proto_Bms5_fields[8];
extern const pb_field_t proto_Bms6_fields[11];
extern const pb_field_t proto_Bms7_fields[7];
extern const pb_field_t proto_Bms8_fields[7];
extern const pb_field_t proto_Bms9_fields[7];
extern const pb_field_t proto_Bms10_fields[7];
extern const pb_field_t proto_Bms11_fields[11];
extern const pb_field_t proto_Bms12_fields[11];
extern const pb_field_t proto_Bms13_fields[7];
extern const pb_field_t proto_Bms14_fields[11];
extern const pb_field_t proto_Bms15_fields[8];
extern const pb_field_t proto_OilPump1_fields[7];
extern const pb_field_t proto_OilPump2_fields[5];
extern const pb_field_t proto_CANMessage_fields[25];
extern const pb_field_t proto_position_data_t_fields[8];

/* Maximum encoded size of messages (where known) */
#define proto_RsuInfoRequest_size                193
/* proto_RsuInfoResponse_size depends on runtime parameters */
#define proto_ObuTrafficLightsRequest_size       101
/* proto_ObuTrafficLightsResponse_size depends on runtime parameters */
#define proto_RoadBlockRequest_size              32
#define proto_RoadBlockResponse_size             28
#define proto_uwb_size                           31
#define proto_Vcu1_size                          49
#define proto_Vcu2_size                          99
#define proto_Vcu3_size                          27
#define proto_Vcu4_size                          35
#define proto_Meter1_size                        127
#define proto_Meter2_size                        27
#define proto_AirCondition_size                  84
#define proto_Bms1_size                          190
#define proto_Bms2_size                          49
#define proto_Bms3_size                          39
#define proto_Bms4_size                          164
#define proto_Bms5_size                          46
#define proto_Bms6_size                          75
#define proto_Bms7_size                          41
#define proto_Bms8_size                          39
#define proto_Bms9_size                          39
#define proto_Bms10_size                         39
#define proto_Bms11_size                         85
#define proto_Bms12_size                         85
#define proto_Bms13_size                         51
#define proto_Bms14_size                         85
#define proto_Bms15_size                         47
#define proto_OilPump1_size                      41
#define proto_OilPump2_size                      29
#define proto_CANMessage_size                    1651
#define proto_position_data_t_size               60

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TEST_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
