/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Jul 17 18:36:56 2019. */

#include "test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t proto_RsuInfoRequest_fields[30] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_RsuInfoRequest, RsuId, RsuId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, Timestamp, RsuId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, NorthSignalL, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, NorthDelayL, NorthSignalL, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, NorthSignalD, NorthDelayL, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, NorthDelayD, NorthSignalD, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, NorthSignalR, NorthDelayD, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, NorthDelayR, NorthSignalR, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, SouthSignalL, NorthDelayR, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, SouthDelayL, SouthSignalL, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, SouthSignalD, SouthDelayL, 0),
    PB_FIELD( 12, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, SouthDelayD, SouthSignalD, 0),
    PB_FIELD( 13, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, SouthSignalR, SouthDelayD, 0),
    PB_FIELD( 14, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, SouthDelayR, SouthSignalR, 0),
    PB_FIELD( 15, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, WestSignalL, SouthDelayR, 0),
    PB_FIELD( 16, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, WestDelayL, WestSignalL, 0),
    PB_FIELD( 17, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, WestSignalD, WestDelayL, 0),
    PB_FIELD( 18, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, WestDelayD, WestSignalD, 0),
    PB_FIELD( 19, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, WestSignalR, WestDelayD, 0),
    PB_FIELD( 20, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, WestDelayR, WestSignalR, 0),
    PB_FIELD( 21, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, EastSignalL, WestDelayR, 0),
    PB_FIELD( 22, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, EastDelayL, EastSignalL, 0),
    PB_FIELD( 23, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, EastSignalD, EastDelayL, 0),
    PB_FIELD( 24, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, EastDelayD, EastSignalD, 0),
    PB_FIELD( 25, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, EastSignalR, EastDelayD, 0),
    PB_FIELD( 26, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, EastDelayR, EastSignalR, 0),
    PB_FIELD( 27, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, SensorRain, EastDelayR, 0),
    PB_FIELD( 28, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, SensorWaterLogged, SensorRain, 0),
    PB_FIELD( 29, UINT32  , SINGULAR, STATIC  , OTHER, proto_RsuInfoRequest, SensorVisibility, SensorWaterLogged, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_RsuInfoResponse_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_RsuInfoResponse, RsuId, RsuId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_RsuInfoResponse, Timestamp, RsuId, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, proto_RsuInfoResponse, Code, Timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_ObuTrafficLightsRequest_fields[15] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_ObuTrafficLightsRequest, VechicleId, VechicleId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, Timestamp, VechicleId, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, VechicleLongitude, Timestamp, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, VechicleLatitude, VechicleLongitude, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, VechicleHeading, VechicleLatitude, 0),
    PB_FIELD(  6, DOUBLE  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, VechicleSpeed, VechicleHeading, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, VechicleForwardTurning, VechicleSpeed, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, VechicleLaneChangingIntention, VechicleForwardTurning, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, VechicleSpeedChangeIntention, VechicleLaneChangingIntention, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, TrafficId, VechicleSpeedChangeIntention, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, TrafficDirection, TrafficId, 0),
    PB_FIELD( 12, UINT32  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, TrafficTrace, TrafficDirection, 0),
    PB_FIELD( 13, UINT32  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, TrafficSignal, TrafficTrace, 0),
    PB_FIELD( 14, UINT32  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsRequest, TrafficDelay, TrafficSignal, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_ObuTrafficLightsResponse_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_ObuTrafficLightsResponse, VechicleId, VechicleId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_ObuTrafficLightsResponse, Timestamp, VechicleId, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, proto_ObuTrafficLightsResponse, Code, Timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_RoadBlockRequest_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_RoadBlockRequest, RsuId, RsuId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_RoadBlockRequest, Timestamp, RsuId, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, proto_RoadBlockRequest, SpeedLimit, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_RoadBlockRequest, latitude, SpeedLimit, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, proto_RoadBlockRequest, longitude, latitude, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_RoadBlockResponse_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_RoadBlockResponse, RsuId, RsuId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_RoadBlockResponse, Time, RsuId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_RoadBlockResponse, Color, Time, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_RoadBlockResponse, SpeedLimit, Color, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_uwb_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_uwb, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_uwb, Timestamp, CarId, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, proto_uwb, NorthHemisphere, Timestamp, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, proto_uwb, EastHemisphere, NorthHemisphere, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, proto_uwb, Latitude, EastHemisphere, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, proto_uwb, Longitude, Latitude, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Vcu1_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Vcu1, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Vcu1, Timestamp, CarId, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Vcu1, MotorControlInputVoltage, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Vcu1, MotorControlInputCurrent, MotorControlInputVoltage, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, proto_Vcu1, MotorTorque, MotorControlInputCurrent, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, proto_Vcu1, MotorSpeed, MotorTorque, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Vcu2_fields[15] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Vcu2, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Vcu2, Timestamp, CarId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, proto_Vcu2, MotorTemperatur, Timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, proto_Vcu2, MotorControlTemperature, MotorTemperatur, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, HighVoltageSwitch, MotorControlTemperature, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, PowerMode, HighVoltageSwitch, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, ClimbMode, PowerMode, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, Gear, ClimbMode, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, EffectiveElectricBrak, Gear, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, ChargDetectionSignal, EffectiveElectricBrak, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, AirConditionerSignal, ChargDetectionSignal, 0),
    PB_FIELD( 12, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, PrechargeContactor, AirConditionerSignal, 0),
    PB_FIELD( 13, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, MasterContactor, PrechargeContactor, 0),
    PB_FIELD( 14, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu2, SystemDemo, MasterContactor, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Vcu3_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Vcu3, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Vcu3, Timestamp, CarId, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Vcu3, TractionPedalPercent, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Vcu3, BrakePedalPercent, TractionPedalPercent, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Vcu4_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Vcu4, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Vcu4, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu4, VehicleModel, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu4, VehicleSystem, VehicleModel, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Vcu4, ElectricalMachinery, VehicleSystem, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Meter1_fields[21] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Meter1, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Meter1, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, KeyFirstGearSignal, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, KeyTwoGearSignal, KeyFirstGearSignal, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, BackDoorOpenSignal, KeyTwoGearSignal, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, FrontDoorOpenSignal, BackDoorOpenSignal, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, RearCompartmentDoorOpenSignal, FrontDoorOpenSignal, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, ParkingSignal, RearCompartmentDoorOpenSignal, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, VehicleLowPressureAlarm, ParkingSignal, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, TurnLeftInstruction, VehicleLowPressureAlarm, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, FarLightInstruction, TurnLeftInstruction, 0),
    PB_FIELD( 12, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, FrontMistInstruction, FarLightInstruction, 0),
    PB_FIELD( 13, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, TurnRightInstruction, FrontMistInstruction, 0),
    PB_FIELD( 14, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, OilMassAlarm, TurnRightInstruction, 0),
    PB_FIELD( 15, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, EnginePreheat, OilMassAlarm, 0),
    PB_FIELD( 16, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, NearLightInstruction, EnginePreheat, 0),
    PB_FIELD( 17, UINT32  , SINGULAR, STATIC  , OTHER, proto_Meter1, BackMistInstruction, NearLightInstruction, 0),
    PB_FIELD( 18, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Meter1, VehicleSpeed, BackMistInstruction, 0),
    PB_FIELD( 19, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Meter1, AirPressureOne, VehicleSpeed, 0),
    PB_FIELD( 20, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Meter1, AirPressureTwo, AirPressureOne, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Meter2_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Meter2, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Meter2, Timestamp, CarId, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Meter2, MeterTotalMileage, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Meter2, MeterPartMileage, MeterTotalMileage, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_AirCondition_fields[12] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_AirCondition, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_AirCondition, Timestamp, CarId, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, proto_AirCondition, ActualAirConditioningLoad, Timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, proto_AirCondition, SetTemperature, ActualAirConditioningLoad, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, proto_AirCondition, CarOutsideTemperature, SetTemperature, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, proto_AirCondition, CarInsideTemperature, CarOutsideTemperature, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, proto_AirCondition, DirectCurrentelEctricity, CarInsideTemperature, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, proto_AirCondition, AirConditionerStatusReady, DirectCurrentelEctricity, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_AirCondition, AirConditionerStatusBreakdown, AirConditionerStatusReady, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, proto_AirCondition, AirConditionerStatusStart, AirConditionerStatusBreakdown, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, proto_AirCondition, LifeValue, AirConditionerStatusStart, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms1_fields[30] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms1, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms1, Timestamp, CarId, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms1, TotalBatteryVoltage, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms1, RechargeDischargeElectricity, TotalBatteryVoltage, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms1, SOCValue, RechargeDischargeElectricity, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, PressureBig, SOCValue, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, TotalOvervoltage, PressureBig, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, TotalUndervoltage, TotalOvervoltage, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, InsideCommunicationFail, TotalUndervoltage, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, SOCLow, InsideCommunicationFail, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, SOCHigt, SOCLow, 0),
    PB_FIELD( 12, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, MonocaseUndervoltage, SOCHigt, 0),
    PB_FIELD( 13, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, MonocaseOvervoltage, MonocaseUndervoltage, 0),
    PB_FIELD( 14, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, TemperatureOverSize, MonocaseOvervoltage, 0),
    PB_FIELD( 15, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, TemperatureRiseOversize, TemperatureOverSize, 0),
    PB_FIELD( 16, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, TemperatureOverTop, TemperatureRiseOversize, 0),
    PB_FIELD( 17, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, RechargeElectricityOverSize, TemperatureOverTop, 0),
    PB_FIELD( 18, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, DischargeElectricityOverSize, RechargeElectricityOverSize, 0),
    PB_FIELD( 19, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, InsulationAlarm, DischargeElectricityOverSize, 0),
    PB_FIELD( 20, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, SmogAlarm, InsulationAlarm, 0),
    PB_FIELD( 21, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, CellTemperatureOverSize, SmogAlarm, 0),
    PB_FIELD( 22, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, FuseStatus, CellTemperatureOverSize, 0),
    PB_FIELD( 23, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, CurrentRechargeStatus, FuseStatus, 0),
    PB_FIELD( 24, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, RechargeConnectSureSignal, CurrentRechargeStatus, 0),
    PB_FIELD( 25, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, CommunicationWithBatteryCharger, RechargeConnectSureSignal, 0),
    PB_FIELD( 26, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, HaveCapacitySmallCell, CommunicationWithBatteryCharger, 0),
    PB_FIELD( 27, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, HaveResistanceBigCell, HaveCapacitySmallCell, 0),
    PB_FIELD( 28, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, InsideContactorSignal, HaveResistanceBigCell, 0),
    PB_FIELD( 29, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms1, RadiatSystemRunning, InsideContactorSignal, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms2_fields[8] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms2, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms2, Timestamp, CarId, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms2, CurrentMaxAllowRechargeElectricity, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms2, CurrentMaxAllowDischargeElectricity, CurrentMaxAllowRechargeElectricity, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms2, LiPoSystemBreakdownClass, CurrentMaxAllowDischargeElectricity, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms2, MonomerMeanVoltage, LiPoSystemBreakdownClass, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms2, MonomerMaxTemperature, MonomerMeanVoltage, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms3_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms3, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms3, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms3, PositiveInsulatingResistance, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms3, NegativeInsulatingResistance, PositiveInsulatingResistance, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms3, CellVoltageMaxValue, NegativeInsulatingResistance, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms3, CellVoltageMinValue, CellVoltageMaxValue, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms4_fields[23] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms4, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms4, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, VINAcceptStatus, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, AssistContactorGlue, VINAcceptStatus, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, ChargingContactorStatus, AssistContactorGlue, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, CellCathodeContactorGlue, ChargingContactorStatus, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, CellAnodeContactorGlue, CellCathodeContactorGlue, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, MSDStatus, CellAnodeContactorGlue, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, WirelessRechargeConnectSignal, MSDStatus, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, ChargingStationOverTemperatureTemperature, WirelessRechargeConnectSignal, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, FireExtinguisherAlarm, ChargingStationOverTemperatureTemperature, 0),
    PB_FIELD( 12, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms4, ChargingStationTemperature1, FireExtinguisherAlarm, 0),
    PB_FIELD( 13, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms4, ChargingStationTemperature2, ChargingStationTemperature1, 0),
    PB_FIELD( 14, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms4, ChargingStationTemperature3, ChargingStationTemperature2, 0),
    PB_FIELD( 15, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms4, ChargingStationTemperature4, ChargingStationTemperature3, 0),
    PB_FIELD( 16, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, ActiveBreakdownCount, ChargingStationTemperature4, 0),
    PB_FIELD( 17, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, ChargeComplete, ActiveBreakdownCount, 0),
    PB_FIELD( 18, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, WarmModuleTurnoff, ChargeComplete, 0),
    PB_FIELD( 19, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, HighPressureTurnoff, WarmModuleTurnoff, 0),
    PB_FIELD( 20, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, CellSystemPilesUnmatched, HighPressureTurnoff, 0),
    PB_FIELD( 21, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, CellOverRecharge, CellSystemPilesUnmatched, 0),
    PB_FIELD( 22, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms4, SOCSaltusStep, CellOverRecharge, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms5_fields[8] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms5, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms5, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms5, CellSystemRatedCapacity, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms5, CellSystemRatedVoltage, CellSystemRatedCapacity, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms5, CellMonomerCascadeNumber, CellSystemRatedVoltage, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms5, CellMonomerMultipleNumber, CellMonomerCascadeNumber, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms5, CellSystemTemperatureProbeNumber, CellMonomerMultipleNumber, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms6_fields[11] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms6, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms6, Timestamp, CarId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms6, CellTemperatureMaxValue, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms6, CellMaxTemperatureCode, CellTemperatureMaxValue, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms6, CellMaxTemperatureNum, CellMaxTemperatureCode, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms6, CellTemperatureMinValue, CellMaxTemperatureNum, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms6, CellMinTemperatureCode, CellTemperatureMinValue, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms6, CellMinTemperatureNum, CellMinTemperatureCode, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms6, CellTypeInfo, CellMinTemperatureNum, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms6, CellCollMode, CellTypeInfo, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms7_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms7, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms7, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms7, CellMaxVoltageCode, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms7, CellMaxVoltageNum, CellMaxVoltageCode, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms7, CellMinVoltageCode, CellMaxVoltageNum, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms7, CellMinVoltageNum, CellMinVoltageCode, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms8_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms8, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms8, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms8, ForwardCellNum1, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms8, ForwardCellVoltage1, ForwardCellNum1, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms8, ForwardCellNum2, ForwardCellVoltage1, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms8, ForwardCellVoltage2, ForwardCellNum2, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms9_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms9, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms9, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms9, ForwardCellNum5, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms9, ForwardCellVoltage5, ForwardCellNum5, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms9, NegativeCellNum1, ForwardCellVoltage5, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms9, NegativeCellVoltage1, NegativeCellNum1, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms10_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms10, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms10, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms10, CellNum1, Timestamp, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms10, CellVoltage1, CellNum1, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms10, CellNum2, CellVoltage1, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, proto_Bms10, CellVoltage2, CellNum2, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms11_fields[11] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms11, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms11, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms11, ForwardSamplingSite1Number, Timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms11, ForwardSamplingSite1Temperature, ForwardSamplingSite1Number, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms11, ForwardSamplingSite2Number, ForwardSamplingSite1Temperature, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms11, ForwardSamplingSite2Temperature, ForwardSamplingSite2Number, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms11, ForwardSamplingSite3Number, ForwardSamplingSite2Temperature, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms11, ForwardSamplingSite3Temperature, ForwardSamplingSite3Number, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms11, ForwardSamplingSite4Number, ForwardSamplingSite3Temperature, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms11, ForwardSamplingSite4Temperature, ForwardSamplingSite4Number, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms12_fields[11] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms12, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms12, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms12, ForwardSamplingSite5Number, Timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms12, ForwardSamplingSite5Temperature, ForwardSamplingSite5Number, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms12, NegativeSamplingSite1Number, ForwardSamplingSite5Temperature, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms12, NegativeSamplingSite1Temperature, NegativeSamplingSite1Number, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms12, NegativeSamplingSite2Number, NegativeSamplingSite1Temperature, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms12, NegativeSamplingSite2Temperature, NegativeSamplingSite2Number, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms12, NegativeSamplingSite3Number, NegativeSamplingSite2Temperature, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms12, NegativeSamplingSite3Temperature, NegativeSamplingSite3Number, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms13_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms13, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms13, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms13, NegativeSamplingSite4Number, Timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms13, NegativeSamplingSite4Temperature, NegativeSamplingSite4Number, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms13, NegativeSamplingSite5Number, NegativeSamplingSite4Temperature, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms13, NegativeSamplingSite5Temperature, NegativeSamplingSite5Number, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms14_fields[11] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms14, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms14, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms14, SamplingSite1Number, Timestamp, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms14, SamplingSite1Temperature, SamplingSite1Number, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms14, SamplingSite2Number, SamplingSite1Temperature, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms14, SamplingSite2Temperature, SamplingSite2Number, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms14, SamplingSite3Number, SamplingSite2Temperature, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms14, SamplingSite3Temperature, SamplingSite3Number, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms14, SamplingSite4Number, SamplingSite3Temperature, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, proto_Bms14, SamplingSite4Temperature, SamplingSite4Number, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Bms15_fields[8] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_Bms15, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_Bms15, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms15, CellPermissibleDisconnectionIdentification, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms15, MainContactorRequestStatus, CellPermissibleDisconnectionIdentification, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms15, ElectricDefrostingContactorRequestStatus, MainContactorRequestStatus, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms15, ElectricHeatingContactorRequestStatus, ElectricDefrostingContactorRequestStatus, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, proto_Bms15, ACContactorRequestStatus, ElectricHeatingContactorRequestStatus, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_OilPump1_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_OilPump1, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_OilPump1, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_OilPump1, MotorSpeed, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_OilPump1, HeartbeatSignal, MotorSpeed, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, proto_OilPump1, HighVoltageFaultMarkerBit, HeartbeatSignal, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, proto_OilPump1, HighVoltageFaultRating, HighVoltageFaultMarkerBit, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_OilPump2_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_OilPump2, CarId, CarId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, proto_OilPump2, Timestamp, CarId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_OilPump2, OilPumpEnabled, Timestamp, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_OilPump2, VehicleSpeed, OilPumpEnabled, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_CANMessage_fields[25] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, proto_CANMessage, Vcu1Msg, Vcu1Msg, &proto_Vcu1_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Vcu2Msg, Vcu1Msg, &proto_Vcu2_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Vcu3Msg, Vcu2Msg, &proto_Vcu3_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Vcu4Msg, Vcu3Msg, &proto_Vcu4_fields),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Meter1Msg, Vcu4Msg, &proto_Meter1_fields),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Meter2Msg, Meter1Msg, &proto_Meter2_fields),
    PB_FIELD(  7, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, AirConditionMsg, Meter2Msg, &proto_AirCondition_fields),
    PB_FIELD(  8, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms1Msg, AirConditionMsg, &proto_Bms1_fields),
    PB_FIELD(  9, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms2Msg, Bms1Msg, &proto_Bms2_fields),
    PB_FIELD( 10, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms3Msg, Bms2Msg, &proto_Bms3_fields),
    PB_FIELD( 11, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms4Msg, Bms3Msg, &proto_Bms4_fields),
    PB_FIELD( 12, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms5Msg, Bms4Msg, &proto_Bms5_fields),
    PB_FIELD( 13, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms6Msg, Bms5Msg, &proto_Bms6_fields),
    PB_FIELD( 14, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms7Msg, Bms6Msg, &proto_Bms7_fields),
    PB_FIELD( 15, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms8Msg, Bms7Msg, &proto_Bms8_fields),
    PB_FIELD( 16, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms9Msg, Bms8Msg, &proto_Bms9_fields),
    PB_FIELD( 17, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms10Msg, Bms9Msg, &proto_Bms10_fields),
    PB_FIELD( 18, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms11Msg, Bms10Msg, &proto_Bms11_fields),
    PB_FIELD( 19, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms12Msg, Bms11Msg, &proto_Bms12_fields),
    PB_FIELD( 20, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms13Msg, Bms12Msg, &proto_Bms13_fields),
    PB_FIELD( 21, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms14Msg, Bms13Msg, &proto_Bms14_fields),
    PB_FIELD( 22, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, Bms15Msg, Bms14Msg, &proto_Bms15_fields),
    PB_FIELD( 23, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, OilPump1Msg, Bms15Msg, &proto_OilPump1_fields),
    PB_FIELD( 24, MESSAGE , SINGULAR, STATIC  , OTHER, proto_CANMessage, OilPump2Msg, OilPump1Msg, &proto_OilPump2_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_position_data_t_fields[5] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, proto_position_data_t, latitude, latitude, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, proto_position_data_t, longitude, latitude, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, proto_position_data_t, heading, longitude, 0),
    PB_FIELD(  4, DOUBLE  , SINGULAR, STATIC  , OTHER, proto_position_data_t, velocity, heading, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_CANMessage, Vcu1Msg) < 65536 && pb_membersize(proto_CANMessage, Vcu2Msg) < 65536 && pb_membersize(proto_CANMessage, Vcu3Msg) < 65536 && pb_membersize(proto_CANMessage, Vcu4Msg) < 65536 && pb_membersize(proto_CANMessage, Meter1Msg) < 65536 && pb_membersize(proto_CANMessage, Meter2Msg) < 65536 && pb_membersize(proto_CANMessage, AirConditionMsg) < 65536 && pb_membersize(proto_CANMessage, Bms1Msg) < 65536 && pb_membersize(proto_CANMessage, Bms2Msg) < 65536 && pb_membersize(proto_CANMessage, Bms3Msg) < 65536 && pb_membersize(proto_CANMessage, Bms4Msg) < 65536 && pb_membersize(proto_CANMessage, Bms5Msg) < 65536 && pb_membersize(proto_CANMessage, Bms6Msg) < 65536 && pb_membersize(proto_CANMessage, Bms7Msg) < 65536 && pb_membersize(proto_CANMessage, Bms8Msg) < 65536 && pb_membersize(proto_CANMessage, Bms9Msg) < 65536 && pb_membersize(proto_CANMessage, Bms10Msg) < 65536 && pb_membersize(proto_CANMessage, Bms11Msg) < 65536 && pb_membersize(proto_CANMessage, Bms12Msg) < 65536 && pb_membersize(proto_CANMessage, Bms13Msg) < 65536 && pb_membersize(proto_CANMessage, Bms14Msg) < 65536 && pb_membersize(proto_CANMessage, Bms15Msg) < 65536 && pb_membersize(proto_CANMessage, OilPump1Msg) < 65536 && pb_membersize(proto_CANMessage, OilPump2Msg) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_proto_RsuInfoRequest_proto_RsuInfoResponse_proto_ObuTrafficLightsRequest_proto_ObuTrafficLightsResponse_proto_RoadBlockRequest_proto_RoadBlockResponse_proto_uwb_proto_Vcu1_proto_Vcu2_proto_Vcu3_proto_Vcu4_proto_Meter1_proto_Meter2_proto_AirCondition_proto_Bms1_proto_Bms2_proto_Bms3_proto_Bms4_proto_Bms5_proto_Bms6_proto_Bms7_proto_Bms8_proto_Bms9_proto_Bms10_proto_Bms11_proto_Bms12_proto_Bms13_proto_Bms14_proto_Bms15_proto_OilPump1_proto_OilPump2_proto_CANMessage_proto_position_data_t)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_CANMessage, Vcu1Msg) < 256 && pb_membersize(proto_CANMessage, Vcu2Msg) < 256 && pb_membersize(proto_CANMessage, Vcu3Msg) < 256 && pb_membersize(proto_CANMessage, Vcu4Msg) < 256 && pb_membersize(proto_CANMessage, Meter1Msg) < 256 && pb_membersize(proto_CANMessage, Meter2Msg) < 256 && pb_membersize(proto_CANMessage, AirConditionMsg) < 256 && pb_membersize(proto_CANMessage, Bms1Msg) < 256 && pb_membersize(proto_CANMessage, Bms2Msg) < 256 && pb_membersize(proto_CANMessage, Bms3Msg) < 256 && pb_membersize(proto_CANMessage, Bms4Msg) < 256 && pb_membersize(proto_CANMessage, Bms5Msg) < 256 && pb_membersize(proto_CANMessage, Bms6Msg) < 256 && pb_membersize(proto_CANMessage, Bms7Msg) < 256 && pb_membersize(proto_CANMessage, Bms8Msg) < 256 && pb_membersize(proto_CANMessage, Bms9Msg) < 256 && pb_membersize(proto_CANMessage, Bms10Msg) < 256 && pb_membersize(proto_CANMessage, Bms11Msg) < 256 && pb_membersize(proto_CANMessage, Bms12Msg) < 256 && pb_membersize(proto_CANMessage, Bms13Msg) < 256 && pb_membersize(proto_CANMessage, Bms14Msg) < 256 && pb_membersize(proto_CANMessage, Bms15Msg) < 256 && pb_membersize(proto_CANMessage, OilPump1Msg) < 256 && pb_membersize(proto_CANMessage, OilPump2Msg) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_proto_RsuInfoRequest_proto_RsuInfoResponse_proto_ObuTrafficLightsRequest_proto_ObuTrafficLightsResponse_proto_RoadBlockRequest_proto_RoadBlockResponse_proto_uwb_proto_Vcu1_proto_Vcu2_proto_Vcu3_proto_Vcu4_proto_Meter1_proto_Meter2_proto_AirCondition_proto_Bms1_proto_Bms2_proto_Bms3_proto_Bms4_proto_Bms5_proto_Bms6_proto_Bms7_proto_Bms8_proto_Bms9_proto_Bms10_proto_Bms11_proto_Bms12_proto_Bms13_proto_Bms14_proto_Bms15_proto_OilPump1_proto_OilPump2_proto_CANMessage_proto_position_data_t)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
